coverage:
  status:
    project:
      v2:
        flags: ["v2"]
        target: "auto"
        threshold: "0.5"
        only_pulls: true
        informational: false

      v1:
        flags: ["v1"]
        target: "auto"
        threshold: "100.0"
        only_pulls: true
        informational: true

      default:
        target: "auto"
        threshold: "2.0"
        informational: true

  ignore:
    - "v2/examples/**"
    - "v2/env"
    - "v2/internal/testutil"
    - "v2/i18n/locales/**"
    - "v2/**/testdata/**"
    - "**/mocks/**"

comment:
  layout: "reach,diff,flags,files,tree"
  behavior: default
  require_changes: false

flags:
  v1:
    carryforward: true
    paths:
      - ./

  v2:
    carryforward: true
    paths:
      - v2/