// Code generated by goopt-i18n-gen. DO NOT EDIT.

package messages

// Keys provides compile-time safe access to translation keys
var Keys = struct {
	AppAudit struct {
		AllFieldsHaveKeys string

		AllHaveKeys string

		AutoUpdating string

		DescLabel string

		FieldDesc string

		FieldInfo string

		FoundFieldsWithoutKeys string

		FoundWithoutKeys string

		GeneratedKey string

		GeneratedKeys string

		GeneratedKeysHeader string

		GeneratedTranslation string

		InFileUpdateTag string

		ManualInstructions string

		TipAutoUpdate string

		TipGenerateKeys string

		TranslationLabel string

		UpdatedFile string

		UpdatedJsonFile string

		UpdatingFiles string
	}

	AppCmdAudit struct {
		AutoUpdateDesc string

		BackupDirDesc string

		FilesDesc string

		GenerateDescKeys string

		GenerateMissing string

		KeyPrefixDesc string
	}

	AppCmd struct {
		AuditDesc string

		GenerateDesc string

		InitDesc string

		ValidateDesc string
	}

	AppCmdGenerate struct {
		OutputDesc string

		PackageDesc string

		PrefixDesc string
	}

	AppCmdInit struct {
		ForceDesc string
	}

	AppCmdValidate struct {
		GenerateMissing string

		ScanDesc string

		StrictDesc string
	}

	App struct {
		Description string

		Name string

		Version string
	}

	AppError struct {
		CommandFailed string

		FailedToCreateDir string

		FailedToCreateFile string

		FailedToCreateOutputDir string

		FailedToExecuteTemplate string

		FailedToExpandInput string

		FailedToExpandPattern string

		FailedToGetConfig string

		FailedToMarshal string

		FailedToParseJson string

		FailedToParseTemplate string

		FailedToPrepareInput string

		FailedToReadInput string

		FailedToWriteJson string

		FailedToWriteOutput string

		NoFiles string

		ParseError string

		ValidationFailed string
	}

	AppGenerate struct {
		FoundKeys string

		FoundKeysInFile string

		Success string

		SuccessVerbose string
	}

	AppGlobal struct {
		HelpDesc string

		InputDesc string

		LanguageDesc string

		VerboseDesc string
	}

	AppInit struct {
		CreatedFile string

		FileExists string

		NextStep1 string

		NextStep2 string

		NextStep3 string

		NextSteps string

		Step1 string

		Step2 string

		Step3 string
	}

	AppTest struct {
		FieldDesc string
	}

	AppValidate struct {
		AllKeysValid string

		AllValid string

		AllValidInFile string

		FoundReferences string

		GeneratingStubs string

		MissingInFile string

		MissingKey string

		MissingTranslations string

		NoFiles string

		StubEntry string

		UpdatedFile string

		UsedInFile string
	}

	AppWarning struct {
		FailedToFormat string

		UpdateFailed string
	}
}{

	AppAudit: struct {
		AllFieldsHaveKeys string

		AllHaveKeys string

		AutoUpdating string

		DescLabel string

		FieldDesc string

		FieldInfo string

		FoundFieldsWithoutKeys string

		FoundWithoutKeys string

		GeneratedKey string

		GeneratedKeys string

		GeneratedKeysHeader string

		GeneratedTranslation string

		InFileUpdateTag string

		ManualInstructions string

		TipAutoUpdate string

		TipGenerateKeys string

		TranslationLabel string

		UpdatedFile string

		UpdatedJsonFile string

		UpdatingFiles string
	}{

		AllFieldsHaveKeys: "app.audit.all_fields_have_keys",

		AllHaveKeys: "app.audit.all_have_keys",

		AutoUpdating: "app.audit.auto_updating",

		DescLabel: "app.audit.desc_label",

		FieldDesc: "app.audit.field_desc",

		FieldInfo: "app.audit.field_info",

		FoundFieldsWithoutKeys: "app.audit.found_fields_without_keys",

		FoundWithoutKeys: "app.audit.found_without_keys",

		GeneratedKey: "app.audit.generated_key",

		GeneratedKeys: "app.audit.generated_keys",

		GeneratedKeysHeader: "app.audit.generated_keys_header",

		GeneratedTranslation: "app.audit.generated_translation",

		InFileUpdateTag: "app.audit.in_file_update_tag",

		ManualInstructions: "app.audit.manual_instructions",

		TipAutoUpdate: "app.audit.tip_auto_update",

		TipGenerateKeys: "app.audit.tip_generate_keys",

		TranslationLabel: "app.audit.translation_label",

		UpdatedFile: "app.audit.updated_file",

		UpdatedJsonFile: "app.audit.updated_json_file",

		UpdatingFiles: "app.audit.updating_files",
	},

	AppCmdAudit: struct {
		AutoUpdateDesc string

		BackupDirDesc string

		FilesDesc string

		GenerateDescKeys string

		GenerateMissing string

		KeyPrefixDesc string
	}{

		AutoUpdateDesc: "app.cmd.audit.auto_update_desc",

		BackupDirDesc: "app.cmd.audit.backup_dir_desc",

		FilesDesc: "app.cmd.audit.files_desc",

		GenerateDescKeys: "app.cmd.audit.generate_desc_keys",

		GenerateMissing: "app.cmd.audit.generate_missing",

		KeyPrefixDesc: "app.cmd.audit.key_prefix_desc",
	},

	AppCmd: struct {
		AuditDesc string

		GenerateDesc string

		InitDesc string

		ValidateDesc string
	}{

		AuditDesc: "app.cmd.audit_desc",

		GenerateDesc: "app.cmd.generate_desc",

		InitDesc: "app.cmd.init_desc",

		ValidateDesc: "app.cmd.validate_desc",
	},

	AppCmdGenerate: struct {
		OutputDesc string

		PackageDesc string

		PrefixDesc string
	}{

		OutputDesc: "app.cmd.generate.output_desc",

		PackageDesc: "app.cmd.generate.package_desc",

		PrefixDesc: "app.cmd.generate.prefix_desc",
	},

	AppCmdInit: struct {
		ForceDesc string
	}{

		ForceDesc: "app.cmd.init.force_desc",
	},

	AppCmdValidate: struct {
		GenerateMissing string

		ScanDesc string

		StrictDesc string
	}{

		GenerateMissing: "app.cmd.validate.generate_missing",

		ScanDesc: "app.cmd.validate.scan_desc",

		StrictDesc: "app.cmd.validate.strict_desc",
	},

	App: struct {
		Description string

		Name string

		Version string
	}{

		Description: "app.description",

		Name: "app.name",

		Version: "app.version",
	},

	AppError: struct {
		CommandFailed string

		FailedToCreateDir string

		FailedToCreateFile string

		FailedToCreateOutputDir string

		FailedToExecuteTemplate string

		FailedToExpandInput string

		FailedToExpandPattern string

		FailedToGetConfig string

		FailedToMarshal string

		FailedToParseJson string

		FailedToParseTemplate string

		FailedToPrepareInput string

		FailedToReadInput string

		FailedToWriteJson string

		FailedToWriteOutput string

		NoFiles string

		ParseError string

		ValidationFailed string
	}{

		CommandFailed: "app.error.command_failed",

		FailedToCreateDir: "app.error.failed_to_create_dir",

		FailedToCreateFile: "app.error.failed_to_create_file",

		FailedToCreateOutputDir: "app.error.failed_to_create_output_dir",

		FailedToExecuteTemplate: "app.error.failed_to_execute_template",

		FailedToExpandInput: "app.error.failed_to_expand_input",

		FailedToExpandPattern: "app.error.failed_to_expand_pattern",

		FailedToGetConfig: "app.error.failed_to_get_config",

		FailedToMarshal: "app.error.failed_to_marshal",

		FailedToParseJson: "app.error.failed_to_parse_json",

		FailedToParseTemplate: "app.error.failed_to_parse_template",

		FailedToPrepareInput: "app.error.failed_to_prepare_input",

		FailedToReadInput: "app.error.failed_to_read_input",

		FailedToWriteJson: "app.error.failed_to_write_json",

		FailedToWriteOutput: "app.error.failed_to_write_output",

		NoFiles: "app.error.no_files",

		ParseError: "app.error.parse_error",

		ValidationFailed: "app.error.validation_failed",
	},

	AppGenerate: struct {
		FoundKeys string

		FoundKeysInFile string

		Success string

		SuccessVerbose string
	}{

		FoundKeys: "app.generate.found_keys",

		FoundKeysInFile: "app.generate.found_keys_in_file",

		Success: "app.generate.success",

		SuccessVerbose: "app.generate.success_verbose",
	},

	AppGlobal: struct {
		HelpDesc string

		InputDesc string

		LanguageDesc string

		VerboseDesc string
	}{

		HelpDesc: "app.global.help_desc",

		InputDesc: "app.global.input_desc",

		LanguageDesc: "app.global.language_desc",

		VerboseDesc: "app.global.verbose_desc",
	},

	AppInit: struct {
		CreatedFile string

		FileExists string

		NextStep1 string

		NextStep2 string

		NextStep3 string

		NextSteps string

		Step1 string

		Step2 string

		Step3 string
	}{

		CreatedFile: "app.init.created_file",

		FileExists: "app.init.file_exists",

		NextStep1: "app.init.next_step_1",

		NextStep2: "app.init.next_step_2",

		NextStep3: "app.init.next_step_3",

		NextSteps: "app.init.next_steps",

		Step1: "app.init.step1",

		Step2: "app.init.step2",

		Step3: "app.init.step3",
	},

	AppTest: struct {
		FieldDesc string
	}{

		FieldDesc: "app.test.field_desc",
	},

	AppValidate: struct {
		AllKeysValid string

		AllValid string

		AllValidInFile string

		FoundReferences string

		GeneratingStubs string

		MissingInFile string

		MissingKey string

		MissingTranslations string

		NoFiles string

		StubEntry string

		UpdatedFile string

		UsedInFile string
	}{

		AllKeysValid: "app.validate.all_keys_valid",

		AllValid: "app.validate.all_valid",

		AllValidInFile: "app.validate.all_valid_in_file",

		FoundReferences: "app.validate.found_references",

		GeneratingStubs: "app.validate.generating_stubs",

		MissingInFile: "app.validate.missing_in_file",

		MissingKey: "app.validate.missing_key",

		MissingTranslations: "app.validate.missing_translations",

		NoFiles: "app.validate.no_files",

		StubEntry: "app.validate.stub_entry",

		UpdatedFile: "app.validate.updated_file",

		UsedInFile: "app.validate.used_in_file",
	},

	AppWarning: struct {
		FailedToFormat string

		UpdateFailed string
	}{

		FailedToFormat: "app.warning.failed_to_format",

		UpdateFailed: "app.warning.update_failed",
	},
}

// K is a shorthand for Keys
var K = Keys
