package types

import (
	"errors"
)

// Core parser errors
var (
	ErrUnsupportedType           = errors.New(ErrUnsupportedTypeKey)
	ErrCommandNotFound           = errors.New(ErrCommandNotFoundKey)
	ErrCommandNoCallback         = errors.New(ErrCommandNoCallbackKey)
	ErrFlagNotFound              = errors.New(ErrFlagNotFoundKey)
	ErrPosixIncompatible         = errors.New(ErrPosixIncompatibleKey)
	ErrValidationFailed          = errors.New(ErrValidationFailedKey)
	ErrBindNil                   = errors.New(ErrBindNilKey)
	ErrNonPointerVar             = errors.New(ErrNonPointerVarKey)
	ErrRequiredFlag              = errors.New(ErrRequiredFlagKey)
	ErrRequiredPositionalFlag    = errors.New(ErrRequiredPositionalFlagKey)
	ErrInvalidArgumentType       = errors.New(ErrInvalidArgumentTypeKey)
	ErrFlagValueNotRetrieved     = errors.New(ErrFlagValueNotRetrievedKey)
	ErrEmptyArgumentPrefixList   = errors.New(ErrEmptyArgumentPrefixListKey)
	ErrEmptyFlag                 = errors.New(ErrEmptyFlagKey)
	ErrFlagAlreadyExists         = errors.New(ErrFlagAlreadyExistsKey)
	ErrPosixShortForm            = errors.New(ErrPosixShortFormKey)
	ErrShortFlagConflict         = errors.New(ErrShortFlagConflictKey)
	ErrInvalidListDelimiterFunc  = errors.New(ErrInvalidListDelimiterFuncKey)
	ErrBindInvalidValue          = errors.New(ErrBindInvalidValueKey)
	ErrPointerExpected           = errors.New(ErrPointerExpectedKey)
	ErrOptionNotSet              = errors.New(ErrOptionNotSetKey)
	ErrLanguageUnavailable       = errors.New(ErrLanguageUnavailableKey)
	ErrShortFlagUndefined        = errors.New(ErrShortFlagUndefinedKey)
	ErrDependencyOnEmptyFlag     = errors.New(ErrDependencyOnEmptyFlagKey)
	ErrRemoveDependencyFromEmpty = errors.New(ErrRemoveDependencyFromEmptyKey)
	ErrSettingBoundValue         = errors.New(ErrSettingBoundValueKey)
	ErrCommandCallbackError      = errors.New(ErrCommandCallbackErrorKey)
	ErrNegativeCapacity          = errors.New(ErrNegativeCapacityKey)
	ErrUnsupportedTypeConversion = errors.New(ErrUnsupportedTypeConversionKey)
	ErrFieldBinding              = errors.New(ErrFieldBindingKey)
	ErrNilPointer                = errors.New(ErrNilPointerKey)
	ErrNoValidTags               = errors.New(ErrNoValidTagsKey)
	ErrInvalidAttributeForType   = errors.New(ErrInvalidAttributeForTypeKey)
)

// Parsing/validation errors
var (
	ErrParseBool     = errors.New(ErrParseBoolKey)
	ErrParseInt      = errors.New(ErrParseIntKey)
	ErrParseFloat    = errors.New(ErrParseFloatKey)
	ErrRegexCompile  = errors.New(ErrRegexCompileKey)
	ErrFileOperation = errors.New(ErrFileOperationKey)
	ErrParseDuration = errors.New(ErrParseDurationKey)
	ErrParseTime     = errors.New(ErrParseTimeKey)
	ErrParseComplex  = errors.New(ErrParseComplexKey)
	ErrParseList     = errors.New(ErrParseListKey)
	ErrParseInt64    = errors.New(ErrParseInt64Key)
	ErrParseInt32    = errors.New(ErrParseInt32Key)
	ErrParseInt16    = errors.New(ErrParseInt16Key)
	ErrParseInt8     = errors.New(ErrParseInt8Key)
	ErrParseOverflow = errors.New(ErrParseOverflowKey)
	ErrParseFloat64  = errors.New(ErrParseFloat64Key)
	ErrParseFloat32  = errors.New(ErrParseFloat32Key)
	ErrParseUint     = errors.New(ErrParseUintKey)
	ErrParseUint64   = errors.New(ErrParseUint64Key)
	ErrParseUint32   = errors.New(ErrParseUint32Key)
	ErrParseUint16   = errors.New(ErrParseUint16Key)
	ErrParseUint8    = errors.New(ErrParseUint8Key)
	ErrParseUintptr  = errors.New(ErrParseUintptrKey)
	ErrWrapped       = errors.New(ErrWrappedKey)
)
