// Code generated by goopt-i18n-gen. DO NOT EDIT.

package messages

// Keys provides compile-time safe access to translation keys
var Keys = struct {
	I18nDemo struct {
		AppDesc string

		DbDesc string

		HelpDesc string

		LangDesc string

		No string

		UserDesc string

		VerboseDesc string

		Yes string
	}

	I18nDemoDbBackup struct {
		BackingUp string

		CompressDesc string

		Executing string

		OutputDesc string

		Success string

		WithCompression string
	}

	I18nDemoDb struct {
		BackupDesc string

		RestoreDesc string
	}

	I18nDemoDbRestore struct {
		DropDesc string

		Dropping string

		Executing string

		InputDesc string

		Restoring string

		Success string
	}

	I18nDemoUserCreate struct {
		AdminDesc string

		Creating string

		EmailDesc string

		Executing string

		Success string

		UsernameDesc string

		WithAdmin string
	}

	I18nDemoUser struct {
		CreateDesc string

		DeleteDesc string

		ListDesc string
	}

	I18nDemoUserDelete struct {
		Confirm string

		Deleting string

		Executing string

		ForceDesc string

		Success string

		UsernameDesc string
	}

	I18nDemoUserList struct {
		AllDesc string

		Executing string

		FormatDesc string

		Header string

		Options string
	}
}{

	I18nDemo: struct {
		AppDesc string

		DbDesc string

		HelpDesc string

		LangDesc string

		No string

		UserDesc string

		VerboseDesc string

		Yes string
	}{

		AppDesc: "i18n.demo.app_desc",

		DbDesc: "i18n.demo.db_desc",

		HelpDesc: "i18n.demo.help_desc",

		LangDesc: "i18n.demo.lang_desc",

		No: "i18n.demo.no",

		UserDesc: "i18n.demo.user_desc",

		VerboseDesc: "i18n.demo.verbose_desc",

		Yes: "i18n.demo.yes",
	},

	I18nDemoDbBackup: struct {
		BackingUp string

		CompressDesc string

		Executing string

		OutputDesc string

		Success string

		WithCompression string
	}{

		BackingUp: "i18n.demo.db.backup.backing_up",

		CompressDesc: "i18n.demo.db.backup.compress_desc",

		Executing: "i18n.demo.db.backup.executing",

		OutputDesc: "i18n.demo.db.backup.output_desc",

		Success: "i18n.demo.db.backup.success",

		WithCompression: "i18n.demo.db.backup.with_compression",
	},

	I18nDemoDb: struct {
		BackupDesc string

		RestoreDesc string
	}{

		BackupDesc: "i18n.demo.db.backup_desc",

		RestoreDesc: "i18n.demo.db.restore_desc",
	},

	I18nDemoDbRestore: struct {
		DropDesc string

		Dropping string

		Executing string

		InputDesc string

		Restoring string

		Success string
	}{

		DropDesc: "i18n.demo.db.restore.drop_desc",

		Dropping: "i18n.demo.db.restore.dropping",

		Executing: "i18n.demo.db.restore.executing",

		InputDesc: "i18n.demo.db.restore.input_desc",

		Restoring: "i18n.demo.db.restore.restoring",

		Success: "i18n.demo.db.restore.success",
	},

	I18nDemoUserCreate: struct {
		AdminDesc string

		Creating string

		EmailDesc string

		Executing string

		Success string

		UsernameDesc string

		WithAdmin string
	}{

		AdminDesc: "i18n.demo.user.create.admin_desc",

		Creating: "i18n.demo.user.create.creating",

		EmailDesc: "i18n.demo.user.create.email_desc",

		Executing: "i18n.demo.user.create.executing",

		Success: "i18n.demo.user.create.success",

		UsernameDesc: "i18n.demo.user.create.username_desc",

		WithAdmin: "i18n.demo.user.create.with_admin",
	},

	I18nDemoUser: struct {
		CreateDesc string

		DeleteDesc string

		ListDesc string
	}{

		CreateDesc: "i18n.demo.user.create_desc",

		DeleteDesc: "i18n.demo.user.delete_desc",

		ListDesc: "i18n.demo.user.list_desc",
	},

	I18nDemoUserDelete: struct {
		Confirm string

		Deleting string

		Executing string

		ForceDesc string

		Success string

		UsernameDesc string
	}{

		Confirm: "i18n.demo.user.delete.confirm",

		Deleting: "i18n.demo.user.delete.deleting",

		Executing: "i18n.demo.user.delete.executing",

		ForceDesc: "i18n.demo.user.delete.force_desc",

		Success: "i18n.demo.user.delete.success",

		UsernameDesc: "i18n.demo.user.delete.username_desc",
	},

	I18nDemoUserList: struct {
		AllDesc string

		Executing string

		FormatDesc string

		Header string

		Options string
	}{

		AllDesc: "i18n.demo.user.list.all_desc",

		Executing: "i18n.demo.user.list.executing",

		FormatDesc: "i18n.demo.user.list.format_desc",

		Header: "i18n.demo.user.list.header",

		Options: "i18n.demo.user.list.options",
	},
}

// K is a shorthand for Keys
var K = Keys
