// Code generated by goopt-i18n-gen. DO NOT EDIT.

package messages

// Keys provides compile-time safe access to translation keys
var Keys = struct {
	AppAppConfigConvert struct {
		FromDesc string

		ToDesc string
	}

	AppAppConfig struct {
		ConvertDesc string

		HelpDesc string

		OutputDesc string

		ProcessDesc string

		VerboseDesc string

		WorkersDesc string
	}

	AppAppConfigProcess struct {
		CompressDesc string

		FormatDesc string

		InputFileDesc string

		ValidateDesc string
	}

	AppAppConfigProcessValidate struct {
		SchemaDesc string

		StrictDesc string
	}
}{

	AppAppConfigConvert: struct {
		FromDesc string

		ToDesc string
	}{

		FromDesc: "app.app_config.convert.from_desc",

		ToDesc: "app.app_config.convert.to_desc",
	},

	AppAppConfig: struct {
		ConvertDesc string

		HelpDesc string

		OutputDesc string

		ProcessDesc string

		VerboseDesc string

		WorkersDesc string
	}{

		ConvertDesc: "app.app_config.convert_desc",

		HelpDesc: "app.app_config.help_desc",

		OutputDesc: "app.app_config.output_desc",

		ProcessDesc: "app.app_config.process_desc",

		VerboseDesc: "app.app_config.verbose_desc",

		WorkersDesc: "app.app_config.workers_desc",
	},

	AppAppConfigProcess: struct {
		CompressDesc string

		FormatDesc string

		InputFileDesc string

		ValidateDesc string
	}{

		CompressDesc: "app.app_config.process.compress_desc",

		FormatDesc: "app.app_config.process.format_desc",

		InputFileDesc: "app.app_config.process.input_file_desc",

		ValidateDesc: "app.app_config.process.validate_desc",
	},

	AppAppConfigProcessValidate: struct {
		SchemaDesc string

		StrictDesc string
	}{

		SchemaDesc: "app.app_config.process.validate.schema_desc",

		StrictDesc: "app.app_config.process.validate.strict_desc",
	},
}

// K is a shorthand for Keys
var K = Keys
