remote_theme: just-the-docs/just-the-docs
title: goopt Documentation
baseurl: "/goopt"  
url: "https://napalu.github.io"
repository: "goopt/napalu" 
color_scheme: nil # auto switching
color_schemes:
  dark: 
    color_scheme: dark
  light: 
    color_scheme: light 
sass:
  sass_dir: _sass
