remote_theme: just-the-docs/just-the-docs
title: goopt Documentation
baseurl: "/goopt"  
url: "https://napalu.github.io"
color_scheme: light # default scheme
color_schemes:
  dark: 
    color_scheme: dark
  light: 
    color_scheme: light 
defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: default
      nav_width: 25% 