package templates

type Field struct {
	Name string
	Key  string
}

type Group struct {
	Name   string
	Fields []Field
}

type TemplateData struct {
	Package string
	Groups  []Group
}

const GeneratedFileTemplate = `// Code generated by goopt-i18n-gen. DO NOT EDIT.

package {{ .Package }}

// Keys provides compile-time safe access to translation keys
var Keys = struct {
{{ range $group := .Groups }}
	{{ $group.Name }} struct {
{{ range $field := $group.Fields }}
		{{ $field.Name }} string
{{ end }}
	}
{{ end }}
}{
{{ range $group := .Groups }}
	{{ $group.Name }}: struct {
{{ range $field := $group.Fields }}
		{{ $field.Name }} string
{{ end }}
	}{
{{ range $field := $group.Fields }}
		{{ $field.Name }}: "{{ $field.Key }}",
{{ end }}
	},
{{ end }}
}

// K is a shorthand for Keys
var K = Keys
`
