name: Test Go Modules (v1 & v2)

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Test & Coverage (v1)
        run: |
          go test -v ./... -covermode=atomic -coverprofile=coverage_v1.out
        shell: bash

      - name: Run Test & Coverage (v2)
        run: |
          go test -v ./... -covermode=atomic -coverprofile=../coverage_v2.out
        working-directory: ./v2
        shell: bash

      - name: List Coverage Files
        run: |
          echo "Working dir: $(pwd)"
          ls -l
          ls -l ./v2 || true
        shell: bash

      - name: Upload Coverage to Codecov (v1)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage_v1.out
          flags: v1
          name: codecov-v1-${{ matrix.os }}-${{ matrix.go-version }}
          fail_ci_if_error: true
          verbose: false
          disable_search: true

      - name: Upload Coverage to Codecov (v2)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage_v2.out
          flags: v2
          name: codecov-v2-${{ matrix.os }}-${{ matrix.go-version }}
          fail_ci_if_error: true
          verbose: false
          disable_search: true